---
- name: Auto-create next WhatsApp bot container
  hosts: localhost
  become: false
  gather_facts: true

  vars:
    base_name: "whatsapp-bot"
    image_name: "whatsapp-bot-api-whatsapp-bot"
    port_start: 3000

  tasks:
    - name: Get list of existing bot containers
      shell: docker ps -a --format '{{ "{{.Names}}" }}' | grep '^{{ base_name }}' || true
      register: bot_names
      changed_when: false

    - name: Ensure bot_names.stdout_lines is at least an empty list
      set_fact:
        existing_bots: "{{ bot_names.stdout_lines | default([]) }}"

    - name: Determine next bot number
      set_fact:
        next_number: >-
          {{
            existing_bots
            | select('match', '^' ~ base_name ~ '\\d+$')
            | map('regex_replace', '^' ~ base_name, '')
            | map('int')
            | list
            | default([0])
            | max
            | int + 1
          }}

    - name: Calculate next bot name and port
      set_fact:
        next_bot_name: "{{ base_name }}{{ next_number }}"
        next_bot_port: "{{ port_start + next_number - 1 }}"

    - name: Run new WhatsApp bot container
      docker_container:
        name: "{{ next_bot_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ next_bot_port }}:3000"
