---
- name: Auto-create next WhatsApp bot container
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    image_name: whatsapp-bot-api-whatsapp-bot
    base_name: client
    base_port: 3000

  tasks:
    - name: Get list of existing bot containers
      command: docker ps -a --format '{{ "{{.Names}}" }}'
      register: bot_names
      changed_when: false

    - name: Ensure bot_names.stdout_lines is at least an empty list
      set_fact:
        container_list: "{{ bot_names.stdout_lines if bot_names.stdout_lines is defined else [] }}"

    - name: Determine next bot number
      set_fact:
        next_number: >-
          {% set max = 0 %}
          {% for name in container_list %}
            {% if name.startswith(base_name) %}
              {% set num = name | regex_replace(base_name, '') | int %}
              {% if num > max %}
                {% set max = num %}
              {% endif %}
            {% endif %}
          {% endfor %}
          {{ max + 1 }}

    - name: Calculate bot name and port
      set_fact:
        bot_name: "{{ base_name }}{{ next_number }}"
        bot_port: "{{ base_port + (next_number | int) - 1 }}"

    - name: Create and run new WhatsApp bot container
      community.docker.docker_container:
        name: "{{ bot_name }}"
        image: "{{ image_name }}"
        restart_policy: unless-stopped
        published_ports:
          - "{{ bot_port }}:3000"
        volumes:
          - "/root/{{ bot_name }}/.wwebjs_auth:/app/.wwebjs_auth"
        env:
          TZ: Asia/Kuala_Lumpur
      vars:
        ansible_python_interpreter: /usr/bin/python3
