---
- name: Auto-create next WhatsApp bot container
  hosts: localhost
  gather_facts: yes
  vars:
    base_name: whatsapp-bot
    port_start: 3000
    image_name: whatsapp-bot-api-whatsapp-bot

  tasks:
    - name: Get list of existing bot containers
      command: docker ps -a --format '{{"{{.Names}}"}}'
      register: bot_names
      changed_when: false

    - name: Ensure bot_names.stdout_lines is at least an empty list
      set_fact:
        container_names: "{{ bot_names.stdout_lines | default([]) }}"

    - name: Determine next bot number
      set_fact:
        existing_bot_numbers: >-
          {{
            container_names
            | select('match', '^' + base_name + '[0-9]+$')
            | map('regex_replace', '^' + base_name, '')
            | map('int')
            | list
          }}

    - name: Set next bot number (handle empty case)
      set_fact:
        next_number: "{{ ((existing_bot_numbers | max) + 1) if existing_bot_numbers | length > 0 else 1 | int }}"

    - name: Calculate bot name and port
      set_fact:
        next_bot_name: "{{ base_name }}{{ next_number }}"
        next_bot_port: "{{ port_start + (next_number | int) - 1 }}"

    - name: Create and run new WhatsApp bot container
      community.docker.docker_container:
        name: "{{ next_bot_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ next_bot_port }}:3000"
        volumes:
          - "/root/clients/{{ next_bot_name }}/session:/app/.wwebjs_auth"
