---
- name: Auto-create next WhatsApp bot container
  hosts: localhost
  become: true
  vars:
    image_name: whatsapp-bot-api-whatsapp-bot
    base_name: whatsapp-bot
    base_port: 3000

  tasks:
    - name: Get list of existing bot containers
      shell: "docker ps -a --format '{{'{{'}}.Names{{'}}'}}' | grep '^{{ base_name }}' || true"
      register: bot_names
      changed_when: false

    - name: Determine next bot number
      set_fact:
        next_bot_number: "{{ (bot_names.stdout_lines | map('regex_replace', '^' ~ base_name ~ '([0-9]*)$', '\\1') | map('int') | default([0]) | max) + 1 }}"

    - name: Set new bot name and port
      set_fact:
        new_bot_name: "{{ base_name }}{{ next_bot_number }}"
        new_port: "{{ base_port + next_bot_number }}"

    - name: Run new bot container
      docker_container:
        name: "{{ new_bot_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ new_port }}:3000"
        env:
          NODE_ENV: production
