---
- name: Automatically create next available WhatsApp bot container
  hosts: localhost
  become: yes
  vars:
    base_name: client
    image_name: whatsapp-bot-api-whatsapp-bot
    port_base: 3000

  tasks:
    - name: Get list of existing bot containers
      shell: >
        docker ps -a --format '{{"{{"}}.Names{{"}}"}}' | grep "^{{ base_name }}" || true
      register: existing_bots
      changed_when: false

    - name: Extract next available index
      set_fact:
        next_index: >-
          {{
            ((existing_bots.stdout_lines | map('regex_search', base_name ~ '([0-9]+)', '\\1') | map('int') | list | max) + 1)
              if existing_bots.stdout_lines else 1
          }}

    - name: Define next bot name and port
      set_fact:
        bot_name: "{{ base_name }}{{ next_index }}"
        port: "{{ port_base + next_index }}"

    - name: Run new WhatsApp bot container
      docker_container:
        name: "{{ bot_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "{{ port }}:3000"
        volumes:
          - "/root/{{ bot_name }}:/app/.wwebjs_auth"

    - name: Print container info
      debug:
        msg: "✅ Started WhatsApp bot container '{{ bot_name }}' on port {{ port }}"
