
version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  backend:
    build: ./backend
    container_name: whatsapp-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/whatsappbot

  frontend:
    build: ./frontend
    container_name: whatsapp-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb-data:
